export const DOCUMENT_TYPES = [
  { id: "pan_applicant", label: "Pan Card (Applicant)", limit: 1 },
  { id: "pan_co_applicant", label: "Pan Card (Co-Applicant)", limit: 1 },
  { id: "aadhar_applicant", label: "Aadhar Card (Applicant)", limit: 1 },
  { id: "aadhar_co_applicant", label: "Aadhar Card (Co-Applicant)", limit: 1 },
  { id: "photo_applicant", label: "Passport Photo (4 Applicant)", limit: 4 },
  { id: "photo_co_applicant",label: "Passport Photo (4 Co-Applicant)",limit: 4 },
  { id: "voter_applicant", label: "Voter Card (Applicant)", limit: 1 },
  { id: "voter_co_applicant", label: "Voter Card (Co-Applicant)", limit: 1 },
  { id: "electric_bill_applicant", label: "Electric Bill (Applicant)", limit: 1 },
  { id: "electric_bill_co_applicant", label: "Electric Bill (Co-Applicant)", limit: 1 },
  { id: "land_patta_applicant", label: "Land Patta (Applicant)", limit: 1 },
  { id: "land_patta_co_applicant", label: "Land Patta (Co-Applicant)", limit: 1 },
  { id: "udyam_cert", label: "Udyam Certificate", limit: 1 },
  { id: "rc_applicant", label: "All R.C (Clear Copy)", limit: 5 },
  { id: "rc_co_applicant", label: "All R.C (Clear Copy)", limit: 5 },
  { id: "loan_stmt_applicant", label: "Loan Statement (If Any)", limit: 2 },
  { id: "bank_stmt_applicant", label: "Bank Statement (6 Months)", limit: 1 },
  { id: "bank_stmt_co_applicant", label: "Bank Statement (6 Months)", limit: 1 },
];
